-- 처음 쓴 코드

SELECT ANIMAL_TYPE,
CASE 
    WHEN NAME IS NULL THEN 'No name'
    ELSE NAME
END AS NAME, SEX_UPON_INTAKE 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

-- COALESCE 함수를 활용한 코드
SELECT ANIMAL_TYPE, COALESCE(NAME, 'No name') AS NAME, SEX_UPON_INTAKE 
-- COALESCE 함수: 두 개 이상의 인자를 받아서, 그 중 '첫 번째로 NULL이 아닌 값'을 반환한다
ORDER BY ANIMAL_ID