SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
    CASE 
        WHEN FREEZER_YN IS NULL THEN 'N' -- 널값이면 N 삽입
        ELSE FREEZER_YN
    END AS FREEZER_YN  
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기도%' -- 주소가 경기도인 창고만 필터링
ORDER BY WAREHOUSE_ID ASC;