SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE 
FROM BOOK 
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
-- BOOK 테이블의 저자 아이디와 AUTHOR 테이블의 저자 아이디가 일치하는 경우에만 합쳐짐
WHERE BOOK.CATEGORY LIKE '%경제%'
ORDER BY BOOK.PUBLISHED_DATE; 